### ISSUE TITLE
Document internal design

### ISSUE THREAD

**Issue by 3asm** [Ostorlab/ostorlab#294]
**Is your feature request related to a problem? Please describe.**
Documentation explaining the internal design of the orchestrator and the different system agents.

**Comment by jamu85** [comment]
Yes please

**Comment by 3asm** [comment]
The first version of the internal design doc is out: https://docs.ostorlab.co/tutorials/life-of-a-scan/.

**Comment by 3asm** [comment]
Thanks, @RabsonJ for preparing this.
