### ISSUE TITLE
How to cleanly uninstall ostorlab?

### ISSUE THREAD

**Issue by gitsang** [Ostorlab/ostorlab#429]
**Is your feature request related to a problem? Please describe.**
After I used `pip uninstall ostrolab` to uninstall, Docker containers `redis-xxxx` and `mq-xxxx` are still running, even if I run `docker rm -f`, they will still be recreated.

**Describe the solution you'd like**
Is there any documentation on how to cleanly uninstall software?

**Describe alternatives you've considered**

**Additional context**
![image](https://github.com/Ostorlab/ostorlab/assets/49085035/9a0033fd-5cf6-4a43-87cb-5224becb677e)

**Comment by 3asm** [comment]
Hi @gitsang ,

The `redis-xxx` and `mq-xxx` are started as Docker Services. To stop them, you can either:

* Use the Ostorlab CLI `ostorlab scan stop <scan-id>`.
* Use Docker CLI to remove the service. `docker service ls` to get the service id and `docker service rm` to remove the service. Or use `docker service rm $(docker service ls -q)` to remove all services.

**Comment by gitsang** [comment]
@3asm Thanks, it help a lot.
